version: '3.9'

services:
  web:
    image: test-react-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: test-react-db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "k&VJB3r892a8@"
      ACCEPT_EULA: "Y"